### ISSUE TITLE
Striptabs

### ISSUE THREAD

**Issue by rdunnion** [RajaSrinivasan/assignments#1]
Here is my solution for striptabs.
https://github.com/rdunnion/striptabs

```
// Ryan Dunnion
// 1/11/21
// This program reads a file and replaces all tabs with a space in the output

#include <iostream>
#include <fstream>

using namespace std;

int main()
{

	char data;
	ifstream inFile("test.txt");

	if (!inFile)
	{
		cerr << "Error.";
	}

	while (inFile.get(data))
	{
		if (data == '\t')
		{
			cout << " ";
		}
		else
		{
			cout << data;
		}
	}

	inFile.close();
	return 0;
}
```

**Comment by RajaSrinivasan** [comment]
Hi Ryan

Thanks for sharing this. Good first attempt

If you are upto a challenge:

in a line, there are (virtual) tab stops at specific columns. Example the
following column numbers may have such a tab stop:

4, 8, 12, 16,.....

So if your current column number is < 4 when you see a tab, you need to
emit enough blanks to set the column to 4 and the next char is printed on
col 4. Similarly if your current column no is 13 or 14 the next char should
appear on col 16.

Of course you go to column no 0 when you see a newline ie "\n"

let me know if you are able to modify your code to function like this. For
testing I will choose tab stops at 8, 16, 24, 32 ....

Good Luck, srini

**Comment by RajaSrinivasan** [comment]
Noted comment
